### ISSUE TITLE
compilation error lzlib.h: No such file or directory

### ISSUE THREAD

**Issue by dulfox** [neuromorphicsystems/lzip#1]
I'm installing lzip (version 1.0.3) on an ARM (64 bits) manjaro OS **from source** (no wheel available):

`$ pip install --no-clean lzip
Collecting lzip
  Using cached lzip-1.0.3.tar.gz (13 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: lzip
  Building wheel for lzip (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for lzip (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-310
      copying lzip.py -> build/lib.linux-aarch64-cpython-310
      running build_ext
      building 'lzip_extension' extension
      creating build/temp.linux-aarch64-cpython-310
      creating build/temp.linux-aarch64-cpython-310/third_party
      creating build/temp.linux-aarch64-cpython-310/third_party/lzlib
      gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/pi/.pyenv/versions/3.10.1/envs/lzip-3.10.1/include -I/home/pi/.pyenv/versions/3.10.1/include/python3.10 -c lzip_extension.cpp -o build/temp.linux-aarch64-cpython-310/lzip_extension.o -std=c++11
      lzip_extension.cpp:1:10: fatal error: third_party/lzlib/lzlib.h: No such file or directory
          1 | #include "third_party/lzlib/lzlib.h"
            |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lzip
Failed to build lzip
ERROR: Could not build wheels for lzip, which is required to install pyproject.toml-based projects`

As I can see in the **local pip installation of lzip-1.0.3.tar.gz** there is no such file:
`.
|-- ./MANIFEST.in
|-- ./PKG-INFO
|-- ./README.md
|-- ./build
|   |-- ./build/lib.linux-aarch64-cpython-310
|   |   `-- ./build/lib.linux-aarch64-cpython-310/lzip.py
|   `-- ./build/temp.linux-aarch64-cpython-310
|       `-- ./build/temp.linux-aarch64-cpython-310/third_party
|           `-- ./build/temp.linux-aarch64-cpython-310/third_party/lzlib
|-- ./lzip.egg-info
|   |-- ./lzip.egg-info/PKG-INFO
|   |-- ./lzip.egg-info/SOURCES.txt
|   |-- ./lzip.egg-info/dependency_links.txt
|   `-- ./lzip.egg-info/top_level.txt
|-- ./lzip.py
|-- ./lzip_extension.cpp
|-- ./pyproject.toml
|-- ./setup.cfg
|-- ./setup.py
`-- ./third_party
    `-- ./third_party/lzlib
        `-- ./third_party/lzlib/lzlib.cpp

8 directories, 14 files`

**Comment by dulfox** [comment]
I've added all the source files from third_party/lzlib and it compiles.

**Comment by aMarcireau** [comment]
Good catch! I forgot to add the lzlib sources to MANIFEST.in. I'll publish a new version on Pypi that should work out of the box (compilation will still be required but pip install should work).
