### ISSUE TITLE
version.py is not included

### ISSUE THREAD

**Issue by dulfox** [neuromorphicsystems/lzip#4]
I've just set a pyenv with the new 1.1.2 (and python 3.10.8) and I get an error when I have imported lzip
```
    import lzip
  File "/home/pi/.pyenv/versions/lzip-3.10.8/lib/python3.10/site-packages/lzip.py", line 7, in <module>
    from version import __version__ as __version__
ModuleNotFoundError: No module named 'version'
```
I've just downloaded version.py on my local site-package and it's working.

I guess the file is missing somewhere.

**Comment by aMarcireau** [comment]
Thanks for the feedback! The new version (1.2.0) should bundle all the files.

**Comment by dulfox** [comment]
Thanks. v1.2.0 is working well.
