### ISSUE TITLE
[request] linux arm64 wheel

### ISSUE THREAD

**Issue by dulfox** [neuromorphicsystems/lzip#5]
I know that not mandatory, but as you provide an arm64 wheel for macos can you please also provide a linux arm64 wheel ?

**Comment by aMarcireau** [comment]
I added 3 Linux architectures to the build pipeline, as described in https://cibuildwheel.readthedocs.io/en/stable/faq/#emulation (aarch64, ppc64le, and s390x). Do they cover your use-cases?

**Comment by dulfox** [comment]
I was able to download via pypi an ARM64 linux wheel. So for me it's ok.
